"""Stable v0 facade for reusable Neural ABM infrastructure.

This module is intentionally narrower than ``neural_abm.__init__``. It exports
the lifecycle, typed social exchange, compatible runner, diagnostics, result,
and readiness surfaces accepted by Decision 0013.
"""

from __future__ import annotations

from neural_abm.capabilities import (
    TOY_TAXONOMY_FIELDS,
    CoordinationCapability,
    ToyCapability,
    supported_toys,
    toy_catalog,
    toy_capability,
    toy_display_name,
    toy_taxonomy_metadata,
    toys_by_taxonomy,
)
from neural_abm.domain_runner import (
    DomainRunSettings,
    DomainToyAdapter,
    DomainToyRunner,
    make_domain_run_dir,
    write_domain_run_metadata,
)
from neural_abm.domain_social_diagnostics import (
    aggregate_social_diagnostic_fields,
    micro_social_diagnostic_fields,
)
from neural_abm.readiness import (
    BinaryReadinessPropagationReport,
    BinaryReadinessPropagationUnit,
    binary_peer_aggregate_values,
    binary_peer_mean_values,
)
from neural_abm.results import (
    DomainToyResult,
    domain_summary_payload,
    write_domain_summary_artifact,
    write_json_artifact,
)
from neural_abm.social import (
    BOUNDED_SCALAR_CHANNEL,
    PROBABILITY_DISTRIBUTION_CHANNEL,
    SCALAR_PROBABILITY_CHANNEL,
    PeerSelectionResult,
    SocialBlock,
    SocialChannel,
    SocialMixResult,
    copy_peer_ids,
    empty_peers,
    mix_bounded_scalars,
    mix_probability_distributions,
    mix_scalar_probabilities,
    peer_ids_for_mixer,
    select_bounded_scalar_output_peers,
    select_distribution_output_peers,
    select_scalar_output_peers,
    validate_peer_ids,
)
from neural_abm.unit import (
    CommitAdapter,
    CommitReport,
    LocalUpdateAdapter,
    LocalUpdateReport,
    NABMAgent,
    NABMLocalStep,
    NABMStep,
    NABMStepResult,
    NABMUnit,
    NABMUnitReport,
    ObservationSpec,
    PeerSelector,
    SocialDiagnostics,
    SocialMessageSpec,
    SocialValueBuilder,
    scalar_message_values,
    social_diagnostics,
    state_dict_values,
    tensor_message_values,
)

__all__ = [
    "BOUNDED_SCALAR_CHANNEL",
    "BinaryReadinessPropagationReport",
    "BinaryReadinessPropagationUnit",
    "CommitAdapter",
    "CommitReport",
    "CoordinationCapability",
    "DomainRunSettings",
    "DomainToyAdapter",
    "DomainToyResult",
    "DomainToyRunner",
    "LocalUpdateAdapter",
    "LocalUpdateReport",
    "NABMAgent",
    "NABMLocalStep",
    "NABMStep",
    "NABMStepResult",
    "NABMUnit",
    "NABMUnitReport",
    "ObservationSpec",
    "PROBABILITY_DISTRIBUTION_CHANNEL",
    "PeerSelectionResult",
    "PeerSelector",
    "SCALAR_PROBABILITY_CHANNEL",
    "SocialBlock",
    "SocialChannel",
    "SocialDiagnostics",
    "SocialMessageSpec",
    "SocialMixResult",
    "SocialValueBuilder",
    "TOY_TAXONOMY_FIELDS",
    "ToyCapability",
    "aggregate_social_diagnostic_fields",
    "binary_peer_aggregate_values",
    "binary_peer_mean_values",
    "copy_peer_ids",
    "domain_summary_payload",
    "empty_peers",
    "make_domain_run_dir",
    "micro_social_diagnostic_fields",
    "mix_bounded_scalars",
    "mix_probability_distributions",
    "mix_scalar_probabilities",
    "peer_ids_for_mixer",
    "scalar_message_values",
    "select_bounded_scalar_output_peers",
    "select_distribution_output_peers",
    "select_scalar_output_peers",
    "social_diagnostics",
    "state_dict_values",
    "supported_toys",
    "tensor_message_values",
    "toy_capability",
    "toy_catalog",
    "toy_display_name",
    "toy_taxonomy_metadata",
    "toys_by_taxonomy",
    "validate_peer_ids",
    "write_domain_run_metadata",
    "write_domain_summary_artifact",
    "write_json_artifact",
]
